### ISSUE TITLE
Errors seem to be swallowed

### ISSUE THREAD

**Issue by vhf** [zazuko/barnard59-graph-store#7]
[This pipeline execution](https://gitlab.zazuko.com/tpluscode/data-cube-curation-example/-/jobs/5571) seem to have ended successfully but it didn't do anything.

Corresponding Stardog logs show:
```
ERROR 2020-03-16 16:31:45,489 [stardog-user-44] com.complexible.stardog.protocols.http.server.ProtocolUtils:rollbackQuietly(624): There was an unexpected error while rolling back the connection
com.complexible.stardog.security.StardogAuthenticationException: Connection user 'null' is not authenticated.
    at com.complexible.stardog.Kernels.assertAuthenticated(Kernels.java:238) ~[stardog-5.3.3.jar:?]
    at com.complexible.stardog.Kernels.assertWritePerms(Kernels.java:211) ~[stardog-5.3.3.jar:?]
    at com.complexible.stardog.StardogKernel$KernelDbConnection.rollback(StardogKernel.java:3280) ~[stardog-5.3.3.jar:?]
    at com.complexible.stardog.db.DelegatingDatabaseConnection.rollback(DelegatingDatabaseConnection.java:312) ~[stardog-5.3.3.jar:?]
    at com.complexible.stardog.StardogKernel$NotifyingDatabaseConnection.rollback(StardogKernel.java:3582) ~[stardog-5.3.3.jar:?]
    at com.complexible.stardog.protocols.http.server.ProtocolUtils.rollbackQuietly(ProtocolUtils.java:620) ~[stardog-protocols-http-server-5.3.3.jar:?]
    at com.complexible.stardog.protocols.http.server.GraphStoreProtocol.setGraph(GraphStoreProtocol.java:185) ~[stardog-protocols-http-server-5.3.3.jar:?]
    at com.stardog.http.server.undertow.jaxrs.ExtractRoutes.lambda$handleIt$5(ExtractRoutes.java:192) ~[stardog-protocols-http-server-5.3.3.jar:?]
    at org.apache.shiro.subject.support.SubjectRunnable.doRun(SubjectRunnable.java:120) [shiro-core-1.3.0.jar:1.3.0]
    at org.apache.shiro.subject.support.SubjectRunnable.run(SubjectRunnable.java:108) [shiro-core-1.3.0.jar:1.3.0]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_181]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_181]
    at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
ERROR 2020-03-16 16:31:45,489 [stardog-user-44] com.complexible.stardog.protocols.http.server.StardogHttpServiceLoader:accept(229): An unexpected exception was handled by the server
com.complexible.stardog.security.StardogAuthenticationException: Connection user 'null' is not authenticated.
    at com.complexible.stardog.Kernels.assertAuthenticated(Kernels.java:238) ~[stardog-5.3.3.jar:?]
    at com.complexible.stardog.Kernels.assertWritePerms(Kernels.java:211) ~[stardog-5.3.3.jar:?]
    at com.complexible.stardog.StardogKernel$KernelDbConnection.add(StardogKernel.java:3350) ~[stardog-5.3.3.jar:?]
    at com.complexible.stardog.db.DelegatingDatabaseConnection.add(DelegatingDatabaseConnection.java:225) ~[stardog-5.3.3.jar:?]
    at com.complexible.stardog.StardogKernel$NotifyingDatabaseConnection.add(StardogKernel.java:3448) ~[stardog-5.3.3.jar:?]
    at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:419) ~[?:1.8.0_181]
    at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580) ~[?:1.8.0_181]
    at com.complexible.stardog.protocols.http.server.GraphStoreProtocol.setGraph(GraphStoreProtocol.java:180) ~[stardog-protocols-http-server-5.3.3.jar:?]
    at com.stardog.http.server.undertow.jaxrs.ExtractRoutes.lambda$handleIt$5(ExtractRoutes.java:192) ~[stardog-protocols-http-server-5.3.3.jar:?]
    at org.apache.shiro.subject.support.SubjectRunnable.doRun(SubjectRunnable.java:120) [shiro-core-1.3.0.jar:1.3.0]
    at org.apache.shiro.subject.support.SubjectRunnable.run(SubjectRunnable.java:108) [shiro-core-1.3.0.jar:1.3.0]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_181]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_181]
    at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
```

According to @martinmaillard:
> It doesn't seem to check the type of response it gets

**Comment by bergos** [comment]
I guess the server sent a 400 or 500 status code. In the latest version [response.ok](https://fetch.spec.whatwg.org/#dom-response-ok) is checked and if it's false an error is emitted using the [statusText](https://fetch.spec.whatwg.org/#dom-response-statustext) as message.

Please give feedback if this problem is solved now. Otherwise I would need more details about the server response.

**Comment by vhf** [comment]
Alright I tried and the same thing happened. I created triples with broken data: `"2014-01-04T00"^^xsd:dateTime` and ran the pipeline after upgrading this package to 0.0.5:

```
❯ npm run start

> data-cube-curation-cli@0.0.0 start /data-cube-curation/packages/cli
> dotenv -- npm run start:transform


> data-cube-curation-cli@0.0.0 start:transform /data-cube-curation/packages/cli
> ts-node index.ts transform --from s3 --to graph-store --project $TRANSFORM_PROJECT --debug -v s3endpoint=$S3_ENDPOINT -v s3bucket=$S3_BUCKET -v graph-store-endpoint=$GRAPH_STORE_ENDPOINT -v graph-store-user=$GRAPH_STORE_USER -v graph-store-password=$GRAPH_STORE_PASSWORD -v graph=$TRANSFORM_GRAPH

  data-cube Running project <…snip…> +0ms
  barnard59:runner variables via CLI: +0ms
  barnard59:runner variables in pipeline instance: +4ms
  barnard59:runner INFO urn:pipeline:data-cube-curation#Main initializing pipeline +1ms
  barnard59:runner INFO urn:pipeline:data-cube-curation#mergeInputs step init +3ms
  barnard59:runner INFO urn:pipeline:data-cube-curation#linkObservationsToDataset step init +12ms
  barnard59:runner INFO urn:pipeline:data-cube-curation#streamOutputStep step init +3s
  barnard59:runner INFO urn:pipeline:data-cube-curation#linkObservationsToDataset step created +206ms
  barnard59:runner INFO urn:pipeline:data-cube-curation#mergeInputs step created +0ms
  barnard59:runner INFO urn:pipeline:data-cube-curation#streamOutputStep step created +0ms
  barnard59:runner INFO urn:pipeline:data-cube-curation#DatacubeMetadata initializing pipeline +1ms
  barnard59:runner INFO urn:pipeline:data-cube-curation#loadDatacubeMetadataStep step init +1ms
  barnard59:runner INFO urn:pipeline:data-cube-curation#parseDatacubeMetadata step init +1ms
  barnard59:runner INFO urn:pipeline:data-cube-curation#accumulateToDataset step init +44ms
  barnard59:runner INFO urn:pipeline:data-cube-curation#generateDatacubeMetadata step init +1ms
  barnard59:runner INFO urn:pipeline:data-cube-curation#parseDatacubeMetadata step created +6ms
  barnard59:runner INFO urn:pipeline:data-cube-curation#accumulateToDataset step created +0ms
  barnard59:runner INFO urn:pipeline:data-cube-curation#generateDatacubeMetadata step created +0ms
  barnard59:runner INFO urn:pipeline:data-cube-curation#loadDatacubeMetadataStep step created +0ms
  barnard59:runner INFO urn:pipeline:data-cube-curation#LoadDatacubeMetadata initializing pipeline +0ms
  barnard59:runner INFO urn:pipeline:data-cube-curation#loadDatacubeMetadata step init +1ms
  barnard59:runner INFO urn:pipeline:data-cube-curation#loadDatacubeMetadata Opening file datacube-metadata.ttl from S3 +3ms
  barnard59:runner INFO urn:pipeline:data-cube-curation#loadDatacubeMetadata step created +196ms
  barnard59:runner INFO urn:pipeline:data-cube-curation#loadDatacubeMetadataStep step finished +11ms
  barnard59:runner INFO urn:pipeline:data-cube-curation#StreamOutput initializing pipeline +3ms
  barnard59:runner INFO b3_setGraph step init +1ms
  barnard59:runner INFO b3_upload step init +1ms
  barnard59:runner INFO b3_setGraph step created +27ms
  barnard59:runner INFO b3_upload step created +0ms
  barnard59:runner INFO urn:pipeline:data-cube-curation#TransformFiles initializing pipeline +10ms
  barnard59:runner INFO urn:pipeline:data-cube-curation#loadMetadata step init +1ms
  barnard59:runner INFO urn:pipeline:data-cube-curation#doTransform step init +2s
  barnard59:runner DEBUG urn:pipeline:data-cube-curation#loadMetadata Loading project <…snip…> +5ms
  barnard59:runner INFO urn:pipeline:data-cube-curation#loadMetadata step created +3ms
  barnard59:runner INFO urn:pipeline:data-cube-curation#doTransform step created +0ms
  barnard59:runner INFO urn:pipeline:data-cube-curation#loadMetadata Will transform project BFE test +582ms
  barnard59:runner DEBUG urn:pipeline:data-cube-curation#loadMetadata Loading output tables <…snip…>/tables +0ms
  barnard59:runner DEBUG urn:pipeline:data-cube-curation#loadMetadata Loading csvw for table Region +287ms
  barnard59:runner DEBUG urn:pipeline:data-cube-curation#loadMetadata Loading csvw for table Scenario +8ms
  barnard59:runner DEBUG urn:pipeline:data-cube-curation#loadMetadata Loading csvw for table Technology +7ms
  barnard59:runner DEBUG urn:pipeline:data-cube-curation#loadMetadata Loading csvw for table Variant +5ms
  barnard59:runner DEBUG urn:pipeline:data-cube-curation#loadMetadata Loading csvw for table measurements +4ms
  barnard59:runner DEBUG urn:pipeline:data-cube-curation#loadMetadata Will transform table Scenario from broken.csv. Dialect: delimiter=, quote=" +3s
  barnard59:runner INFO urn:pipeline:data-cube-curation#TransformCsv initializing pipeline +1ms
  barnard59:runner INFO urn:pipeline:data-cube-curation#loadCsvStep step init +0ms
  barnard59:runner INFO urn:pipeline:data-cube-curation#parse step init +1ms
  barnard59:runner INFO urn:pipeline:data-cube-curation#filterNotCsvw step init +1ms
  barnard59:runner INFO urn:pipeline:data-cube-curation#loadCsvStep step created +217ms
  barnard59:runner INFO urn:pipeline:data-cube-curation#filterNotCsvw step created +0ms
  barnard59:runner INFO urn:pipeline:data-cube-curation#parseMetadata initializing pipeline +0ms
  barnard59:runner INFO urn:pipeline:data-cube-curation#getCsvwGraph step init +0ms
  barnard59:runner INFO urn:pipeline:data-cube-curation#getCsvwGraph step created +225ms
  barnard59:runner INFO urn:pipeline:data-cube-curation#parse step created +7ms
  barnard59:runner INFO urn:pipeline:data-cube-curation#LoadCsv initializing pipeline +0ms
  barnard59:runner INFO b2_openCsvFromBucket step init +1ms
  barnard59:runner INFO b2_openCsvFromBucket Opening file broken.csv from S3 +7ms
  barnard59:runner INFO b2_openCsvFromBucket step created +0ms
  barnard59:runner INFO urn:pipeline:data-cube-curation#loadCsvStep step finished +199ms
  barnard59:runner DEBUG urn:pipeline:data-cube-curation#loadMetadata Will transform table Region from broken.csv. Dialect: delimiter=, quote=" +878ms
  barnard59:runner INFO urn:pipeline:data-cube-curation#TransformCsv initializing pipeline +1ms
  barnard59:runner INFO urn:pipeline:data-cube-curation#loadCsvStep step init +0ms
  barnard59:runner INFO urn:pipeline:data-cube-curation#parse step init +1ms
  barnard59:runner INFO urn:pipeline:data-cube-curation#filterNotCsvw step init +1ms
  barnard59:runner INFO urn:pipeline:data-cube-curation#loadCsvStep step created +7ms
  barnard59:runner INFO urn:pipeline:data-cube-curation#filterNotCsvw step created +0ms
  barnard59:runner INFO urn:pipeline:data-cube-curation#parseMetadata initializing pipeline +0ms
  barnard59:runner INFO urn:pipeline:data-cube-curation#getCsvwGraph step init +0ms
  barnard59:runner INFO urn:pipeline:data-cube-curation#getCsvwGraph step created +6ms
  barnard59:runner INFO urn:pipeline:data-cube-curation#parse step created +3ms
  barnard59:runner INFO urn:pipeline:data-cube-curation#LoadCsv initializing pipeline +0ms
  barnard59:runner INFO b2_openCsvFromBucket step init +0ms
  barnard59:runner INFO b2_openCsvFromBucket Opening file broken.csv from S3 +4ms
  barnard59:runner INFO b2_openCsvFromBucket step created +1ms
  barnard59:runner INFO urn:pipeline:data-cube-curation#loadCsvStep step finished +203ms
  barnard59:runner DEBUG urn:pipeline:data-cube-curation#loadMetadata Will transform table Variant from broken.csv. Dialect: delimiter=, quote=" +178ms
  barnard59:runner INFO urn:pipeline:data-cube-curation#TransformCsv initializing pipeline +1ms
  barnard59:runner INFO urn:pipeline:data-cube-curation#loadCsvStep step init +0ms
  barnard59:runner INFO urn:pipeline:data-cube-curation#parse step init +2ms
  barnard59:runner INFO urn:pipeline:data-cube-curation#filterNotCsvw step init +0ms
  barnard59:runner INFO urn:pipeline:data-cube-curation#loadCsvStep step created +10ms
  barnard59:runner INFO urn:pipeline:data-cube-curation#filterNotCsvw step created +0ms
  barnard59:runner INFO urn:pipeline:data-cube-curation#parseMetadata initializing pipeline +0ms
  barnard59:runner INFO urn:pipeline:data-cube-curation#getCsvwGraph step init +1ms
  barnard59:runner INFO urn:pipeline:data-cube-curation#getCsvwGraph step created +3ms
  barnard59:runner INFO urn:pipeline:data-cube-curation#parse step created +2ms
  barnard59:runner INFO urn:pipeline:data-cube-curation#LoadCsv initializing pipeline +0ms
  barnard59:runner INFO b2_openCsvFromBucket step init +1ms
  barnard59:runner INFO b2_openCsvFromBucket Opening file broken.csv from S3 +3ms
  barnard59:runner INFO b2_openCsvFromBucket step created +1ms
  barnard59:runner DEBUG urn:pipeline:data-cube-curation#loadMetadata Will transform table Technology from broken.csv. Dialect: delimiter=, quote=" +21ms
  barnard59:runner INFO urn:pipeline:data-cube-curation#loadCsvStep step finished +163ms
  barnard59:runner INFO urn:pipeline:data-cube-curation#TransformCsv initializing pipeline +24ms
  barnard59:runner INFO urn:pipeline:data-cube-curation#loadCsvStep step init +0ms
  barnard59:runner INFO urn:pipeline:data-cube-curation#parse step init +1ms
  barnard59:runner INFO urn:pipeline:data-cube-curation#filterNotCsvw step init +0ms
  barnard59:runner INFO urn:pipeline:data-cube-curation#loadCsvStep step created +6ms
  barnard59:runner INFO urn:pipeline:data-cube-curation#filterNotCsvw step created +0ms
  barnard59:runner INFO urn:pipeline:data-cube-curation#parseMetadata initializing pipeline +1ms
  barnard59:runner INFO urn:pipeline:data-cube-curation#getCsvwGraph step init +0ms
  barnard59:runner INFO urn:pipeline:data-cube-curation#getCsvwGraph step created +8ms
  barnard59:runner INFO urn:pipeline:data-cube-curation#parse step created +6ms
  barnard59:runner INFO urn:pipeline:data-cube-curation#LoadCsv initializing pipeline +0ms
  barnard59:runner INFO b2_openCsvFromBucket step init +1ms
  barnard59:runner INFO b2_openCsvFromBucket Opening file broken.csv from S3 +5ms
  barnard59:runner INFO b2_openCsvFromBucket step created +1ms
  barnard59:runner INFO urn:pipeline:data-cube-curation#loadCsvStep step finished +264ms
  barnard59:runner DEBUG urn:pipeline:data-cube-curation#loadMetadata Will transform table measurements from broken.csv. Dialect: delimiter=, quote=" +391ms
  barnard59:runner INFO urn:pipeline:data-cube-curation#TransformCsv initializing pipeline +0ms
  barnard59:runner INFO urn:pipeline:data-cube-curation#loadCsvStep step init +1ms
  barnard59:runner INFO urn:pipeline:data-cube-curation#parse step init +2ms
  barnard59:runner INFO urn:pipeline:data-cube-curation#filterNotCsvw step init +1ms
  barnard59:runner INFO urn:pipeline:data-cube-curation#loadCsvStep step created +7ms
  barnard59:runner INFO urn:pipeline:data-cube-curation#filterNotCsvw step created +0ms
  barnard59:runner INFO urn:pipeline:data-cube-curation#parseMetadata initializing pipeline +0ms
  barnard59:runner INFO urn:pipeline:data-cube-curation#getCsvwGraph step init +0ms
  barnard59:runner INFO urn:pipeline:data-cube-curation#getCsvwGraph step created +3ms
  barnard59:runner INFO urn:pipeline:data-cube-curation#parse step created +4ms
  barnard59:runner INFO urn:pipeline:data-cube-curation#LoadCsv initializing pipeline +0ms
  barnard59:runner INFO b2_openCsvFromBucket step init +0ms
  barnard59:runner INFO b2_openCsvFromBucket Opening file broken.csv from S3 +7ms
  barnard59:runner INFO b2_openCsvFromBucket step created +1ms
  barnard59:runner INFO urn:pipeline:data-cube-curation#loadCsvStep step finished +124ms
  barnard59:runner INFO urn:pipeline:data-cube-curation#streamOutputStep step finished +18ms

❯ so
Last command return code was 0
```

No error, success status, nothing inserted. Stardog logs:

```
WARN  2020-03-26 10:39:36,915 [stardog-user-32] com.complexible.stardog.protocols.http.server.StardogUndertowErrorHandler:accept(61): Unexpected exception was handled by the server
com.stardog.stark.io.InvalidRDF: '2014-01-01T01' is not a valid value for datatype http://www.w3.org/2001/XMLSchema#dateTime [L1060]
        at com.stardog.stark.io.ParserContext.error(ParserContext.java:231) ~[stardog-stark-io-api-7.2.0.jar:?]
        at com.stardog.stark.io.ParserContext.createLiteral(ParserContext.java:278) ~[stardog-stark-io-api-7.2.0.jar:?]
        at com.stardog.stark.io.ntriples.NTParser.parseObject(NTParser.java:264) ~[stardog-stark-io-ntriples-7.2.0.jar:?]
        at com.stardog.stark.io.ntriples.NTParser.parseTriple(NTParser.java:100) ~[stardog-stark-io-ntriples-7.2.0.jar:?]
        at com.stardog.stark.io.ntriples.NTParser.parse(NTParser.java:79) ~[stardog-stark-io-ntriples-7.2.0.jar:?]
        at com.complexible.common.rdf.rio.RDFStreamBuilder$RDFAbstractStream.parse(RDFStreamBuilder.java:300) ~[stardog-utils-rdf-7.2.0.jar:?]
        at com.complexible.common.rdf.rio.RDFStreamBuilder$RDFAbstractStream.parse(RDFStreamBuilder.java:260) ~[stardog-utils-rdf-7.2.0.jar:?]
        at com.complexible.common.rdf.rio.RDFStreamBuilder.parse(RDFStreamBuilder.java:129) ~[stardog-utils-rdf-7.2.0.jar:?]
        at com.complexible.common.rdf.rio.RDFStreamBuilder.parseInto(RDFStreamBuilder.java:138) ~[stardog-utils-rdf-7.2.0.jar:?]
        at com.complexible.common.rdf.impl.StreamStatementSources$ReusableStreamSourceCreator.readIntoMemory(StreamStatementSources.java:278) ~[stardog-utils-rdf-7.2.0.jar:?]
        at com.complexible.common.rdf.impl.StreamStatementSources$ReusableStreamSourceCreator.create(StreamStatementSources.java:247) ~[stardog-utils-rdf-7.2.0.jar:?]
        at com.complexible.stardog.protocols.http.server.ProtocolUtils.parseBody(ProtocolUtils.java:359) ~[stardog-protocols-http-server-7.2.0.jar:?]
        at com.complexible.stardog.protocols.http.server.GraphStoreProtocol.setGraph(GraphStoreProtocol.java:168) ~[stardog-protocols-http-server-7.2.0.jar:?]
        at com.stardog.http.server.undertow.jaxrs.ExtractRoutes.lambda$handleIt$5(ExtractRoutes.java:192) ~[stardog-protocols-http-server-7.2.0.jar:?]
        at org.apache.shiro.subject.support.SubjectRunnable.doRun(SubjectRunnable.java:120) [shiro-core-1.3.0.jar:1.3.0]
        at org.apache.shiro.subject.support.SubjectRunnable.run(SubjectRunnable.java:108) [shiro-core-1.3.0.jar:1.3.0]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_242]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_242]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
debug2: channel 0: window 998740 sent adjust 49836
```

**Comment by tpluscode** [comment]
There is a similar problem when the store URL is not resolvable (unreachable domain, etc)

The actual request originates in [sparql-http-client](https://github.com/zazuko/sparql-http-client/blob/master/StreamStore.js#L99-L112) and adding a `.catch` one can inspect the exception.

But as it is now it gets swallowed somewhere

**Comment by ktk** [comment]
I did a test with local stardog (7.4.x), there seems to be a problem in stardog that returns "socket hang up" from fetch/node. In TCP dump I see that it simply sends a TCP `FIN` after I try to write invalid data to the store.

That error seems to be catched when we talk to Stardog directly, as in I get a `FetchError` and the pipeline fails as expected.

When using it on LINDAS there is probably a nginx proxy in front and for my test pipeline I then get a `bad request` back and the pipeline also fails properly.

So in these two cases it looks like it fails properly.

**Comment by ktk** [comment]
Update I was wrong on "socket hang up", I tried to post to an endpoint that does not exist and there I get the socket error. 7.x behaves with 400 bad request as well to wrong data (and that is catched).

**Comment by ktk** [comment]
In last weeks discussion I remembered that I had the "hang" effect on one of our pipelines, in there I do:

```turtle
<#mergeInputs> a :Step;
  code:implementedBy [
    code:link <node:barnard59-base#concat.object> ;
    a code:EcmaScript
  ] ;
  code:arguments ( <#didok> <#addMetadata> <#GO> ) .rollover limit
```

I first had a different order and there the upload went wrong, if I remember correctly the pipeline hung (it's been a while so not 100% sure anymore).

In other words by flipping the order I got it working. I talked to @bergos and we came to the conclusion it could be related to how the Graph Store protocol is implemented. Node seems to have a memory leak in `fetch` so when we have too large datasets, we eat up memory on the client. So Graph Store protocol solves that by splitting the PUT into a PUT followed by one or more POSTs so we "reset" the `fetch`call. It could be that there is something going wrong there or that an error does get properly propagated through the stack when we have a similar situation.

So I wonder if we run into a similar issue here, that's at least something to dive more into. There is a default "rollover" limit in the Graph Store protocol implementation so an easy way to test that would be to set that higher than the maximum amount of triples we write. If the problem still occurs, it's probably something else.

**Comment by l00mi** [comment]
@bergos you mentioned this is now somehow solved?

**Comment by tpluscode** [comment]
@l00mi https://github.com/zazuko/barnard59-core/pull/58

It may not exactly address what @vhf reported but fixes https://github.com/zazuko/cube-creator/issues/276

**Comment by l00mi** [comment]
Thank you @tpluscode .
Do we keep this one open @vhf? Can you cross check with https://github.com/zazuko/barnard59-core/pull/58 please?

**Comment by bergos** [comment]
I was never able to reproduce it without a sub-pipeline with a Writable interface, which would be fixed with https://github.com/zazuko/barnard59-core/pull/58. I think this issue can be closed.

**Comment by vhf** [comment]
I have no way of checking so let's close and we'll reopen if need be.
